[2022-10-17 10:52:12,889] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.is_api_available backfill__2019-01-01T00:00:00+00:00 [queued]>
[2022-10-17 10:52:12,897] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.is_api_available backfill__2019-01-01T00:00:00+00:00 [queued]>
[2022-10-17 10:52:12,897] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:52:12,897] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 10:52:12,897] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:52:12,906] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2019-01-01 00:00:00+00:00
[2022-10-17 10:52:12,909] {standard_task_runner.py:52} INFO - Started process 5136 to run task
[2022-10-17 10:52:12,912] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'is_api_available', 'backfill__2019-01-01T00:00:00+00:00', '--job-id', '199', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpgcnwmgnv', '--error-file', '/tmp/tmpm4orzlqs']
[2022-10-17 10:52:12,913] {standard_task_runner.py:80} INFO - Job 199: Subtask is_api_available
[2022-10-17 10:52:12,949] {task_command.py:369} INFO - Running <TaskInstance: my_first_dag.is_api_available backfill__2019-01-01T00:00:00+00:00 [running]> on host 48b5b9061ccc
[2022-10-17 10:52:13,044] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=backfill__2019-01-01T00:00:00+00:00
[2022-10-17 10:52:13,045] {http.py:97} INFO - Poking: users/
[2022-10-17 10:52:13,057] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-10-17 10:52:13,063] {http.py:129} INFO - Sending 'GET' to url:  https://random-data-api.com/api/v2/users/
[2022-10-17 10:52:13,930] {base.py:301} INFO - Success criteria met. Exiting.
[2022-10-17 10:52:13,942] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=is_api_available, execution_date=20190101T000000, start_date=20221017T105212, end_date=20221017T105213
[2022-10-17 10:52:13,976] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-17 10:52:13,999] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
