[2022-10-17 10:38:17,996] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_table backfill__2022-01-05T00:00:00+00:00 [queued]>
[2022-10-17 10:38:18,025] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_table backfill__2022-01-05T00:00:00+00:00 [queued]>
[2022-10-17 10:38:18,037] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:38:18,039] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 10:38:18,045] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:38:18,108] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-01-05 00:00:00+00:00
[2022-10-17 10:38:18,124] {standard_task_runner.py:52} INFO - Started process 4268 to run task
[2022-10-17 10:38:18,157] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'create_table', 'backfill__2022-01-05T00:00:00+00:00', '--job-id', '120', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpjk0qi5al', '--error-file', '/tmp/tmpbyyrewb5']
[2022-10-17 10:38:18,171] {standard_task_runner.py:80} INFO - Job 120: Subtask create_table
[2022-10-17 10:38:18,441] {task_command.py:369} INFO - Running <TaskInstance: my_first_dag.create_table backfill__2022-01-05T00:00:00+00:00 [running]> on host 48b5b9061ccc
[2022-10-17 10:38:18,633] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-01-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=backfill__2022-01-05T00:00:00+00:00
[2022-10-17 10:38:18,654] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-17 10:38:18,661] {dbapi.py:208} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS users2 (
            firstname TEXT NOT NULL,
            lastname TEXT NOT NULL,
            username TEXT NOT NULL,
            password TEXT NOT NULL,
            email TEXT NOT NULL
        );
        , parameters: None
[2022-10-17 10:38:18,664] {postgres.py:94} INFO - NOTICE:  relation "users2" already exists, skipping

[2022-10-17 10:38:18,698] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=create_table, execution_date=20220105T000000, start_date=20221017T103818, end_date=20221017T103818
[2022-10-17 10:38:18,788] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-17 10:38:18,861] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
