[2022-10-17 10:33:01,682] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.store_user manual__2022-10-17T10:32:54.309653+00:00 [queued]>
[2022-10-17 10:33:01,689] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.store_user manual__2022-10-17T10:32:54.309653+00:00 [queued]>
[2022-10-17 10:33:01,690] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:33:01,690] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 10:33:01,690] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:33:01,699] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_user> on 2022-10-17 10:32:54.309653+00:00
[2022-10-17 10:33:01,704] {standard_task_runner.py:52} INFO - Started process 3975 to run task
[2022-10-17 10:33:01,706] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'store_user', 'manual__2022-10-17T10:32:54.309653+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmptuc4ogmq', '--error-file', '/tmp/tmpsz8mlnfu']
[2022-10-17 10:33:01,707] {standard_task_runner.py:80} INFO - Job 104: Subtask store_user
[2022-10-17 10:33:01,748] {task_command.py:369} INFO - Running <TaskInstance: my_first_dag.store_user manual__2022-10-17T10:32:54.309653+00:00 [running]> on host 48b5b9061ccc
[2022-10-17 10:33:01,802] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2022-10-17T10:32:54.309653+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-17T10:32:54.309653+00:00
[2022-10-17 10:33:01,803] {postgres.py:127} INFO - Running copy expert: COPY users2 FROM stdin WITH DELIMITER AS ',', filename: /tmp/processed_user.csv
[2022-10-17 10:33:01,810] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-17 10:33:01,815] {python.py:173} INFO - Done. Returned value was: None
[2022-10-17 10:33:01,824] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=store_user, execution_date=20221017T103254, start_date=20221017T103301, end_date=20221017T103301
[2022-10-17 10:33:01,839] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-17 10:33:01,862] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
