[2022-10-17 09:34:02,803] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_table backfill__2022-09-23T00:00:00+00:00 [queued]>
[2022-10-17 09:34:02,862] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_table backfill__2022-09-23T00:00:00+00:00 [queued]>
[2022-10-17 09:34:02,870] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 09:34:02,872] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 09:34:02,876] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 09:34:02,934] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-09-23 00:00:00+00:00
[2022-10-17 09:34:02,960] {standard_task_runner.py:52} INFO - Started process 998 to run task
[2022-10-17 09:34:03,007] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'create_table', 'backfill__2022-09-23T00:00:00+00:00', '--job-id', '34', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmplpwfqft5', '--error-file', '/tmp/tmp5fgr_npq']
[2022-10-17 09:34:03,029] {standard_task_runner.py:80} INFO - Job 34: Subtask create_table
[2022-10-17 09:34:03,345] {task_command.py:369} INFO - Running <TaskInstance: my_first_dag.create_table backfill__2022-09-23T00:00:00+00:00 [running]> on host 48b5b9061ccc
[2022-10-17 09:34:03,855] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=backfill__2022-09-23T00:00:00+00:00
[2022-10-17 09:34:03,893] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-17 09:34:03,903] {dbapi.py:208} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS users2 (
            firstname TEXT NOT NULL,
            lastname TEXT NOT NULL,
            username TEXT NOT NULL,
            password TEXT NOT NULL,
            email TEXT NOT NULL
        );
        , parameters: None
[2022-10-17 09:34:03,911] {postgres.py:94} INFO - NOTICE:  relation "users2" already exists, skipping

[2022-10-17 09:34:03,938] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=create_table, execution_date=20220923T000000, start_date=20221017T093402, end_date=20221017T093403
[2022-10-17 09:34:04,079] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-17 09:34:04,226] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
