[2022-10-17 09:34:02,773] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_table backfill__2022-09-13T00:00:00+00:00 [queued]>
[2022-10-17 09:34:02,856] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_table backfill__2022-09-13T00:00:00+00:00 [queued]>
[2022-10-17 09:34:02,858] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 09:34:02,858] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 09:34:02,859] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 09:34:02,924] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-09-13 00:00:00+00:00
[2022-10-17 09:34:02,946] {standard_task_runner.py:52} INFO - Started process 996 to run task
[2022-10-17 09:34:03,026] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'create_table', 'backfill__2022-09-13T00:00:00+00:00', '--job-id', '28', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpjf5u743i', '--error-file', '/tmp/tmpkjmfpaj7']
[2022-10-17 09:34:03,031] {standard_task_runner.py:80} INFO - Job 28: Subtask create_table
[2022-10-17 09:34:03,331] {task_command.py:369} INFO - Running <TaskInstance: my_first_dag.create_table backfill__2022-09-13T00:00:00+00:00 [running]> on host 48b5b9061ccc
[2022-10-17 09:34:03,839] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=backfill__2022-09-13T00:00:00+00:00
[2022-10-17 09:34:03,876] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-17 09:34:03,894] {dbapi.py:208} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS users2 (
            firstname TEXT NOT NULL,
            lastname TEXT NOT NULL,
            username TEXT NOT NULL,
            password TEXT NOT NULL,
            email TEXT NOT NULL
        );
        , parameters: None
[2022-10-17 09:34:03,900] {postgres.py:94} INFO - NOTICE:  relation "users2" already exists, skipping

[2022-10-17 09:34:03,942] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=create_table, execution_date=20220913T000000, start_date=20221017T093402, end_date=20221017T093403
[2022-10-17 09:34:04,107] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-17 09:34:04,229] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
