[2022-10-17 10:51:18,023] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.store_user manual__2022-10-17T10:51:03.915266+00:00 [queued]>
[2022-10-17 10:51:18,030] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.store_user manual__2022-10-17T10:51:03.915266+00:00 [queued]>
[2022-10-17 10:51:18,030] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:51:18,030] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 10:51:18,030] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:51:18,039] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_user> on 2022-10-17 10:51:03.915266+00:00
[2022-10-17 10:51:18,043] {standard_task_runner.py:52} INFO - Started process 5080 to run task
[2022-10-17 10:51:18,047] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'store_user', 'manual__2022-10-17T10:51:03.915266+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpro8v2xk6', '--error-file', '/tmp/tmpye9njp27']
[2022-10-17 10:51:18,048] {standard_task_runner.py:80} INFO - Job 193: Subtask store_user
[2022-10-17 10:51:18,087] {task_command.py:369} INFO - Running <TaskInstance: my_first_dag.store_user manual__2022-10-17T10:51:03.915266+00:00 [running]> on host 48b5b9061ccc
[2022-10-17 10:51:18,137] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2022-10-17T10:51:03.915266+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-17T10:51:03.915266+00:00
[2022-10-17 10:51:18,139] {postgres.py:127} INFO - Running copy expert: COPY users2 FROM stdin WITH DELIMITER AS ',', filename: /tmp/processed_user.csv
[2022-10-17 10:51:18,145] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-17 10:51:18,150] {python.py:173} INFO - Done. Returned value was: None
[2022-10-17 10:51:18,160] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=store_user, execution_date=20221017T105103, start_date=20221017T105118, end_date=20221017T105118
[2022-10-17 10:51:18,179] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-17 10:51:18,204] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
